# Generated by Django 4.2.7 on 2023-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0005_profile_content_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
